# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.create_user_mfa_verification200_response_one_of import CreateUserMfaVerification200ResponseOneOf

class TestCreateUserMfaVerification200ResponseOneOf(unittest.TestCase):
    """CreateUserMfaVerification200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUserMfaVerification200ResponseOneOf:
        """Test CreateUserMfaVerification200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserMfaVerification200ResponseOneOf`
        """
        model = CreateUserMfaVerification200ResponseOneOf()
        if include_optional:
            return CreateUserMfaVerification200ResponseOneOf(
                type = '',
                secret = '',
                secret_qr_code = ''
            )
        else:
            return CreateUserMfaVerification200ResponseOneOf(
                type = '',
                secret = '',
                secret_qr_code = '',
        )
        """

    def testCreateUserMfaVerification200ResponseOneOf(self):
        """Test CreateUserMfaVerification200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
