# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.api.hooks_api import HooksApi


class TestHooksApi(unittest.TestCase):
    """HooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_hook(self) -> None:
        """Test case for create_hook

        Create a hook
        """
        pass

    def test_create_hook_test(self) -> None:
        """Test case for create_hook_test

        Test hook
        """
        pass

    def test_delete_hook(self) -> None:
        """Test case for delete_hook

        Delete hook
        """
        pass

    def test_get_hook(self) -> None:
        """Test case for get_hook

        Get hook
        """
        pass

    def test_list_hook_recent_logs(self) -> None:
        """Test case for list_hook_recent_logs

        Get recent logs for a hook
        """
        pass

    def test_list_hooks(self) -> None:
        """Test case for list_hooks

        Get hooks
        """
        pass

    def test_update_hook(self) -> None:
        """Test case for update_hook

        Update hook
        """
        pass

    def test_update_hook_signing_key(self) -> None:
        """Test case for update_hook_signing_key

        Update signing key for a hook
        """
        pass


if __name__ == '__main__':
    unittest.main()
