# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.update_organization_scope_request import UpdateOrganizationScopeRequest

class TestUpdateOrganizationScopeRequest(unittest.TestCase):
    """UpdateOrganizationScopeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateOrganizationScopeRequest:
        """Test UpdateOrganizationScopeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateOrganizationScopeRequest`
        """
        model = UpdateOrganizationScopeRequest()
        if include_optional:
            return UpdateOrganizationScopeRequest(
                tenant_id = '',
                id = '0',
                name = '0',
                description = ''
            )
        else:
            return UpdateOrganizationScopeRequest(
        )
        """

    def testUpdateOrganizationScopeRequest(self):
        """Test UpdateOrganizationScopeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
