# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_interaction_verification_webauthn_registration_post200_response_authenticator_selection import ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection

class TestApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection(unittest.TestCase):
    """ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection:
        """Test ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection`
        """
        model = ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection()
        if include_optional:
            return ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection(
                authenticator_attachment = 'platform',
                require_resident_key = True,
                resident_key = 'discouraged',
                user_verification = 'required'
            )
        else:
            return ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection(
        )
        """

    def testApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection(self):
        """Test ApiInteractionVerificationWebauthnRegistrationPost200ResponseAuthenticatorSelection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
