# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_connectors_post_request import ApiConnectorsPostRequest

class TestApiConnectorsPostRequest(unittest.TestCase):
    """ApiConnectorsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiConnectorsPostRequest:
        """Test ApiConnectorsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiConnectorsPostRequest`
        """
        model = ApiConnectorsPostRequest()
        if include_optional:
            return ApiConnectorsPostRequest(
                config = None,
                connector_id = '0',
                metadata = py_logto.models._api_connectors_post_request_metadata._api_connectors_post_request_metadata(
                    target = '', 
                    name = py_logto.models.name.name(), 
                    logo = '', 
                    logo_dark = '', ),
                sync_profile = True,
                id = '0'
            )
        else:
            return ApiConnectorsPostRequest(
                connector_id = '0',
        )
        """

    def testApiConnectorsPostRequest(self):
        """Test ApiConnectorsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
