# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_sso_connectors_post_request import ApiSsoConnectorsPostRequest

class TestApiSsoConnectorsPostRequest(unittest.TestCase):
    """ApiSsoConnectorsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSsoConnectorsPostRequest:
        """Test ApiSsoConnectorsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSsoConnectorsPostRequest`
        """
        model = ApiSsoConnectorsPostRequest()
        if include_optional:
            return ApiSsoConnectorsPostRequest(
                config = None,
                domains = [
                    ''
                    ],
                branding = py_logto.models._api_sso_connectors_get_200_response_inner_branding._api_sso_connectors_get_200_response_inner_branding(
                    display_name = '', 
                    logo = '', 
                    dark_logo = '', ),
                sync_profile = True,
                provider_name = '0',
                connector_name = '0'
            )
        else:
            return ApiSsoConnectorsPostRequest(
                provider_name = '0',
                connector_name = '0',
        )
        """

    def testApiSsoConnectorsPostRequest(self):
        """Test ApiSsoConnectorsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
