# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_interaction_submit_post200_response import ApiInteractionSubmitPost200Response

class TestApiInteractionSubmitPost200Response(unittest.TestCase):
    """ApiInteractionSubmitPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiInteractionSubmitPost200Response:
        """Test ApiInteractionSubmitPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiInteractionSubmitPost200Response`
        """
        model = ApiInteractionSubmitPost200Response()
        if include_optional:
            return ApiInteractionSubmitPost200Response(
                redirect_to = ''
            )
        else:
            return ApiInteractionSubmitPost200Response(
                redirect_to = '',
        )
        """

    def testApiInteractionSubmitPost200Response(self):
        """Test ApiInteractionSubmitPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
