# coding: utf-8

"""
    Python SDK for Logto API

    Python SDK for Logto API.  Note: This SDK is for Logto Cloud and OSS. However, if you are using Logto OSS, some features available in the SDK may not work for you. Please refer to the response of `/api/swagger.json` endpoint on your Logto OSS instance for features available to you.

    The version of the OpenAPI document: 1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.api.well_known_api import WellKnownApi


class TestWellKnownApi(unittest.TestCase):
    """WellKnownApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WellKnownApi()

    def tearDown(self) -> None:
        pass

    def test_get_sign_in_experience_config(self) -> None:
        """Test case for get_sign_in_experience_config

        Get full sign-in experience
        """
        pass

    def test_get_sign_in_experience_phrases(self) -> None:
        """Test case for get_sign_in_experience_phrases

        Get localized phrases
        """
        pass

    def test_get_well_known_experience(self) -> None:
        """Test case for get_well_known_experience

        Get full sign-in experience
        """
        pass

    def test_get_well_known_experience_openapi_json(self) -> None:
        """Test case for get_well_known_experience_openapi_json

        Get Experience API swagger JSON
        """
        pass

    def test_get_well_known_management_openapi_json(self) -> None:
        """Test case for get_well_known_management_openapi_json

        Get Management API swagger JSON
        """
        pass

    def test_get_well_known_user_openapi_json(self) -> None:
        """Test case for get_well_known_user_openapi_json

        Get User API swagger JSON
        """
        pass


if __name__ == '__main__':
    unittest.main()
