# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_hooks_get200_response_inner_execution_stats import ApiHooksGet200ResponseInnerExecutionStats

class TestApiHooksGet200ResponseInnerExecutionStats(unittest.TestCase):
    """ApiHooksGet200ResponseInnerExecutionStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiHooksGet200ResponseInnerExecutionStats:
        """Test ApiHooksGet200ResponseInnerExecutionStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiHooksGet200ResponseInnerExecutionStats`
        """
        model = ApiHooksGet200ResponseInnerExecutionStats()
        if include_optional:
            return ApiHooksGet200ResponseInnerExecutionStats(
                success_count = 1.337,
                request_count = 1.337
            )
        else:
            return ApiHooksGet200ResponseInnerExecutionStats(
                success_count = 1.337,
                request_count = 1.337,
        )
        """

    def testApiHooksGet200ResponseInnerExecutionStats(self):
        """Test ApiHooksGet200ResponseInnerExecutionStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
