# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.create_organization_role_request import CreateOrganizationRoleRequest

class TestCreateOrganizationRoleRequest(unittest.TestCase):
    """CreateOrganizationRoleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrganizationRoleRequest:
        """Test CreateOrganizationRoleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrganizationRoleRequest`
        """
        model = CreateOrganizationRoleRequest()
        if include_optional:
            return CreateOrganizationRoleRequest(
                tenant_id = '',
                name = '0',
                description = '',
                type = 'User',
                organization_scope_ids = [
                    ''
                    ],
                resource_scope_ids = [
                    ''
                    ]
            )
        else:
            return CreateOrganizationRoleRequest(
                name = '0',
                organization_scope_ids = [
                    ''
                    ],
                resource_scope_ids = [
                    ''
                    ],
        )
        """

    def testCreateOrganizationRoleRequest(self):
        """Test CreateOrganizationRoleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
