# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.list_logs200_response_inner_payload import ListLogs200ResponseInnerPayload

class TestListLogs200ResponseInnerPayload(unittest.TestCase):
    """ListLogs200ResponseInnerPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListLogs200ResponseInnerPayload:
        """Test ListLogs200ResponseInnerPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListLogs200ResponseInnerPayload`
        """
        model = ListLogs200ResponseInnerPayload()
        if include_optional:
            return ListLogs200ResponseInnerPayload(
                key = '',
                result = 'Success',
                error = None,
                ip = '',
                user_agent = '',
                user_id = '',
                application_id = '',
                session_id = ''
            )
        else:
            return ListLogs200ResponseInnerPayload(
                key = '',
                result = 'Success',
        )
        """

    def testListLogs200ResponseInnerPayload(self):
        """Test ListLogs200ResponseInnerPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
