# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.get_jwt_customizer200_response_one_of_context_sample_user_profile_address import GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress

class TestGetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress(unittest.TestCase):
    """GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress:
        """Test GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress`
        """
        model = GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress()
        if include_optional:
            return GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress(
                formatted = '',
                street_address = '',
                locality = '',
                region = '',
                postal_code = '',
                country = ''
            )
        else:
            return GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress(
        )
        """

    def testGetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress(self):
        """Test GetJwtCustomizer200ResponseOneOfContextSampleUserProfileAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
