# coding: utf-8

"""
    Python SDK for Logto API

    Python SDK for Logto API.  Note: This SDK is for Logto Cloud and OSS. However, if you are using Logto OSS, some features available in the SDK may not work for you. Please refer to the response of `/api/swagger.json` endpoint on your Logto OSS instance for features available to you.

    The version of the OpenAPI document: 1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_create_domain(self) -> None:
        """Test case for create_domain

        Create domain
        """
        pass

    def test_delete_domain(self) -> None:
        """Test case for delete_domain

        Delete domain
        """
        pass

    def test_get_domain(self) -> None:
        """Test case for get_domain

        Get domain
        """
        pass

    def test_list_domains(self) -> None:
        """Test case for list_domains

        Get domains
        """
        pass


if __name__ == '__main__':
    unittest.main()
