# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.assert_single_sign_on_saml_request import AssertSingleSignOnSamlRequest

class TestAssertSingleSignOnSamlRequest(unittest.TestCase):
    """AssertSingleSignOnSamlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssertSingleSignOnSamlRequest:
        """Test AssertSingleSignOnSamlRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssertSingleSignOnSamlRequest`
        """
        model = AssertSingleSignOnSamlRequest()
        if include_optional:
            return AssertSingleSignOnSamlRequest(
                relay_state = '',
                saml_response = ''
            )
        else:
            return AssertSingleSignOnSamlRequest(
                relay_state = '',
                saml_response = '',
        )
        """

    def testAssertSingleSignOnSamlRequest(self):
        """Test AssertSingleSignOnSamlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
