# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_configs_jwt_customizer_token_type_path_get200_response_one_of_context_sample_user_organization_roles_inner import ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner

class TestApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner(unittest.TestCase):
    """ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner:
        """Test ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner`
        """
        model = ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner()
        if include_optional:
            return ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner(
                organization_id = '',
                role_id = '',
                role_name = ''
            )
        else:
            return ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner(
                organization_id = '',
                role_id = '',
                role_name = '',
        )
        """

    def testApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner(self):
        """Test ApiConfigsJwtCustomizerTokenTypePathGet200ResponseOneOfContextSampleUserOrganizationRolesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
