# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.get_sign_in_exp200_response_mfa import GetSignInExp200ResponseMfa

class TestGetSignInExp200ResponseMfa(unittest.TestCase):
    """GetSignInExp200ResponseMfa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSignInExp200ResponseMfa:
        """Test GetSignInExp200ResponseMfa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSignInExp200ResponseMfa`
        """
        model = GetSignInExp200ResponseMfa()
        if include_optional:
            return GetSignInExp200ResponseMfa(
                factors = [
                    'Totp'
                    ],
                policy = 'UserControlled'
            )
        else:
            return GetSignInExp200ResponseMfa(
                factors = [
                    'Totp'
                    ],
                policy = 'UserControlled',
        )
        """

    def testGetSignInExp200ResponseMfa(self):
        """Test GetSignInExp200ResponseMfa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
