# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.create_connector_authorization_uri200_response import CreateConnectorAuthorizationUri200Response

class TestCreateConnectorAuthorizationUri200Response(unittest.TestCase):
    """CreateConnectorAuthorizationUri200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConnectorAuthorizationUri200Response:
        """Test CreateConnectorAuthorizationUri200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConnectorAuthorizationUri200Response`
        """
        model = CreateConnectorAuthorizationUri200Response()
        if include_optional:
            return CreateConnectorAuthorizationUri200Response(
                redirect_to = '',
                redirect_uri = None
            )
        else:
            return CreateConnectorAuthorizationUri200Response(
                redirect_to = '',
        )
        """

    def testCreateConnectorAuthorizationUri200Response(self):
        """Test CreateConnectorAuthorizationUri200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
