# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.update_sign_in_exp200_response_color import UpdateSignInExp200ResponseColor

class TestUpdateSignInExp200ResponseColor(unittest.TestCase):
    """UpdateSignInExp200ResponseColor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSignInExp200ResponseColor:
        """Test UpdateSignInExp200ResponseColor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSignInExp200ResponseColor`
        """
        model = UpdateSignInExp200ResponseColor()
        if include_optional:
            return UpdateSignInExp200ResponseColor(
                primary_color = '#bf3',
                is_dark_mode_enabled = True,
                dark_primary_color = '#bf3'
            )
        else:
            return UpdateSignInExp200ResponseColor(
                primary_color = '#bf3',
                is_dark_mode_enabled = True,
                dark_primary_color = '#bf3',
        )
        """

    def testUpdateSignInExp200ResponseColor(self):
        """Test UpdateSignInExp200ResponseColor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
