# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.assign_organization_roles_to_applications_request import AssignOrganizationRolesToApplicationsRequest

class TestAssignOrganizationRolesToApplicationsRequest(unittest.TestCase):
    """AssignOrganizationRolesToApplicationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssignOrganizationRolesToApplicationsRequest:
        """Test AssignOrganizationRolesToApplicationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssignOrganizationRolesToApplicationsRequest`
        """
        model = AssignOrganizationRolesToApplicationsRequest()
        if include_optional:
            return AssignOrganizationRolesToApplicationsRequest(
                application_ids = [
                    '0'
                    ],
                organization_role_ids = [
                    '0'
                    ]
            )
        else:
            return AssignOrganizationRolesToApplicationsRequest(
                application_ids = [
                    '0'
                    ],
                organization_role_ids = [
                    '0'
                    ],
        )
        """

    def testAssignOrganizationRolesToApplicationsRequest(self):
        """Test AssignOrganizationRolesToApplicationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
