# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_interaction_put_request_identifier_one_of4 import ApiInteractionPutRequestIdentifierOneOf4

class TestApiInteractionPutRequestIdentifierOneOf4(unittest.TestCase):
    """ApiInteractionPutRequestIdentifierOneOf4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiInteractionPutRequestIdentifierOneOf4:
        """Test ApiInteractionPutRequestIdentifierOneOf4
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiInteractionPutRequestIdentifierOneOf4`
        """
        model = ApiInteractionPutRequestIdentifierOneOf4()
        if include_optional:
            return ApiInteractionPutRequestIdentifierOneOf4(
                phone = '4',
                verification_code = '0'
            )
        else:
            return ApiInteractionPutRequestIdentifierOneOf4(
                phone = '4',
                verification_code = '0',
        )
        """

    def testApiInteractionPutRequestIdentifierOneOf4(self):
        """Test ApiInteractionPutRequestIdentifierOneOf4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
