# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.get_sign_in_experience_config200_response_google_one_tap import GetSignInExperienceConfig200ResponseGoogleOneTap

class TestGetSignInExperienceConfig200ResponseGoogleOneTap(unittest.TestCase):
    """GetSignInExperienceConfig200ResponseGoogleOneTap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSignInExperienceConfig200ResponseGoogleOneTap:
        """Test GetSignInExperienceConfig200ResponseGoogleOneTap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSignInExperienceConfig200ResponseGoogleOneTap`
        """
        model = GetSignInExperienceConfig200ResponseGoogleOneTap()
        if include_optional:
            return GetSignInExperienceConfig200ResponseGoogleOneTap(
                is_enabled = True,
                auto_select = True,
                close_on_tap_outside = True,
                itp_support = True,
                client_id = '',
                connector_id = ''
            )
        else:
            return GetSignInExperienceConfig200ResponseGoogleOneTap(
                client_id = '',
                connector_id = '',
        )
        """

    def testGetSignInExperienceConfig200ResponseGoogleOneTap(self):
        """Test GetSignInExperienceConfig200ResponseGoogleOneTap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
