# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_connectors_factory_id_test_post_request import ApiConnectorsFactoryIdTestPostRequest

class TestApiConnectorsFactoryIdTestPostRequest(unittest.TestCase):
    """ApiConnectorsFactoryIdTestPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiConnectorsFactoryIdTestPostRequest:
        """Test ApiConnectorsFactoryIdTestPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiConnectorsFactoryIdTestPostRequest`
        """
        model = ApiConnectorsFactoryIdTestPostRequest()
        if include_optional:
            return ApiConnectorsFactoryIdTestPostRequest(
                phone = '4',
                email = 'k@?x!u'K}qz^sEC)lJ*=-jQ+'6`%cClu,k'!'su[..zF6V,V6rEtCO?&28nxs#k8z)\"\\6\\%TMxo:-sWVoim9gs',
                config = None
            )
        else:
            return ApiConnectorsFactoryIdTestPostRequest(
                config = None,
        )
        """

    def testApiConnectorsFactoryIdTestPostRequest(self):
        """Test ApiConnectorsFactoryIdTestPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
