# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.create_connector_request import CreateConnectorRequest

class TestCreateConnectorRequest(unittest.TestCase):
    """CreateConnectorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateConnectorRequest:
        """Test CreateConnectorRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConnectorRequest`
        """
        model = CreateConnectorRequest()
        if include_optional:
            return CreateConnectorRequest(
                config = None,
                connector_id = '0',
                metadata = py_logto.models.create_connector_request_metadata.CreateConnector_request_metadata(
                    target = '', 
                    name = py_logto.models.name.name(), 
                    logo = '', 
                    logo_dark = '', ),
                sync_profile = True,
                id = '0'
            )
        else:
            return CreateConnectorRequest(
                connector_id = '0',
        )
        """

    def testCreateConnectorRequest(self):
        """Test CreateConnectorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
