# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.list_connectors200_response_inner_form_items_inner_one_of1_select_items_inner import ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner

class TestListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner(unittest.TestCase):
    """ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner:
        """Test ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner`
        """
        model = ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner()
        if include_optional:
            return ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner(
                value = ''
            )
        else:
            return ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner(
                value = '',
        )
        """

    def testListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner(self):
        """Test ListConnectors200ResponseInnerFormItemsInnerOneOf1SelectItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
