# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.get_jwt_customizer200_response import GetJwtCustomizer200Response

class TestGetJwtCustomizer200Response(unittest.TestCase):
    """GetJwtCustomizer200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJwtCustomizer200Response:
        """Test GetJwtCustomizer200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJwtCustomizer200Response`
        """
        model = GetJwtCustomizer200Response()
        if include_optional:
            return GetJwtCustomizer200Response(
                script = '',
                environment_variables = {
                    'key' : ''
                    },
                context_sample = py_logto.models.context_sample.contextSample(),
                token_sample = py_logto.models.get_jwt_customizer_200_response_one_of_1_token_sample.GetJwtCustomizer_200_response_oneOf_1_tokenSample(
                    jti = '', 
                    aud = null, 
                    scope = '', 
                    client_id = '', 
                    kind = '', )
            )
        else:
            return GetJwtCustomizer200Response(
                script = '',
        )
        """

    def testGetJwtCustomizer200Response(self):
        """Test GetJwtCustomizer200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
