# coding: utf-8

"""
    Python SDK for Logto API

    Python SDK for Logto API.  Note: This SDK is for Logto Cloud and OSS. However, if you are using Logto OSS, some features available in the SDK may not work for you. Please refer to the response of `/api/swagger.json` endpoint on your Logto OSS instance for features available to you.

    The version of the OpenAPI document: 1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.api.configs_api import ConfigsApi


class TestConfigsApi(unittest.TestCase):
    """ConfigsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_jwt_customizer(self) -> None:
        """Test case for delete_jwt_customizer

        Delete JWT customizer
        """
        pass

    def test_delete_oidc_key(self) -> None:
        """Test case for delete_oidc_key

        Delete OIDC key
        """
        pass

    def test_get_admin_console_config(self) -> None:
        """Test case for get_admin_console_config

        Get admin console config
        """
        pass

    def test_get_jwt_customizer(self) -> None:
        """Test case for get_jwt_customizer

        Get JWT customizer
        """
        pass

    def test_get_oidc_keys(self) -> None:
        """Test case for get_oidc_keys

        Get OIDC keys
        """
        pass

    def test_list_jwt_customizers(self) -> None:
        """Test case for list_jwt_customizers

        Get all JWT customizers
        """
        pass

    def test_rotate_oidc_keys(self) -> None:
        """Test case for rotate_oidc_keys

        Rotate OIDC keys
        """
        pass

    def test_test_jwt_customizer(self) -> None:
        """Test case for test_jwt_customizer

        Test JWT customizer
        """
        pass

    def test_update_admin_console_config(self) -> None:
        """Test case for update_admin_console_config

        Update admin console config
        """
        pass

    def test_update_jwt_customizer(self) -> None:
        """Test case for update_jwt_customizer

        Update JWT customizer
        """
        pass

    def test_upsert_jwt_customizer(self) -> None:
        """Test case for upsert_jwt_customizer

        Create or update JWT customizer
        """
        pass


if __name__ == '__main__':
    unittest.main()
