# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.api.well_known_api import WellKnownApi


class TestWellKnownApi(unittest.TestCase):
    """WellKnownApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WellKnownApi()

    def tearDown(self) -> None:
        pass

    def test_api_well_known_phrases_get(self) -> None:
        """Test case for api_well_known_phrases_get

        Get localized phrases
        """
        pass

    def test_api_well_known_sign_in_exp_get(self) -> None:
        """Test case for api_well_known_sign_in_exp_get

        Get full sign-in experience
        """
        pass


if __name__ == '__main__':
    unittest.main()
