# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.update_sign_in_exp200_response_password_policy import UpdateSignInExp200ResponsePasswordPolicy

class TestUpdateSignInExp200ResponsePasswordPolicy(unittest.TestCase):
    """UpdateSignInExp200ResponsePasswordPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSignInExp200ResponsePasswordPolicy:
        """Test UpdateSignInExp200ResponsePasswordPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSignInExp200ResponsePasswordPolicy`
        """
        model = UpdateSignInExp200ResponsePasswordPolicy()
        if include_optional:
            return UpdateSignInExp200ResponsePasswordPolicy(
                length = py_logto.models.get_sign_in_exp_200_response_password_policy_length.GetSignInExp_200_response_passwordPolicy_length(
                    min = 1.337, 
                    max = 1.337, ),
                character_types = py_logto.models.get_sign_in_exp_200_response_password_policy_character_types.GetSignInExp_200_response_passwordPolicy_characterTypes(
                    min = 1.337, ),
                rejects = py_logto.models.get_sign_in_exp_200_response_password_policy_rejects.GetSignInExp_200_response_passwordPolicy_rejects(
                    pwned = True, 
                    repetition_and_sequence = True, 
                    user_info = True, 
                    words = [
                        ''
                        ], )
            )
        else:
            return UpdateSignInExp200ResponsePasswordPolicy(
        )
        """

    def testUpdateSignInExp200ResponsePasswordPolicy(self):
        """Test UpdateSignInExp200ResponsePasswordPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
