# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.add_organization_users_request import AddOrganizationUsersRequest

class TestAddOrganizationUsersRequest(unittest.TestCase):
    """AddOrganizationUsersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddOrganizationUsersRequest:
        """Test AddOrganizationUsersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddOrganizationUsersRequest`
        """
        model = AddOrganizationUsersRequest()
        if include_optional:
            return AddOrganizationUsersRequest(
                user_ids = [
                    '0'
                    ]
            )
        else:
            return AddOrganizationUsersRequest(
                user_ids = [
                    '0'
                    ],
        )
        """

    def testAddOrganizationUsersRequest(self):
        """Test AddOrganizationUsersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
