# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.assign_organization_roles_to_user_request import AssignOrganizationRolesToUserRequest

class TestAssignOrganizationRolesToUserRequest(unittest.TestCase):
    """AssignOrganizationRolesToUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssignOrganizationRolesToUserRequest:
        """Test AssignOrganizationRolesToUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssignOrganizationRolesToUserRequest`
        """
        model = AssignOrganizationRolesToUserRequest()
        if include_optional:
            return AssignOrganizationRolesToUserRequest(
                organization_role_ids = [
                    '0'
                    ]
            )
        else:
            return AssignOrganizationRolesToUserRequest(
                organization_role_ids = [
                    '0'
                    ],
        )
        """

    def testAssignOrganizationRolesToUserRequest(self):
        """Test AssignOrganizationRolesToUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
