# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.replace_organization_jit_email_domains_request import ReplaceOrganizationJitEmailDomainsRequest

class TestReplaceOrganizationJitEmailDomainsRequest(unittest.TestCase):
    """ReplaceOrganizationJitEmailDomainsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplaceOrganizationJitEmailDomainsRequest:
        """Test ReplaceOrganizationJitEmailDomainsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplaceOrganizationJitEmailDomainsRequest`
        """
        model = ReplaceOrganizationJitEmailDomainsRequest()
        if include_optional:
            return ReplaceOrganizationJitEmailDomainsRequest(
                email_domains = [
                    ''
                    ]
            )
        else:
            return ReplaceOrganizationJitEmailDomainsRequest(
                email_domains = [
                    ''
                    ],
        )
        """

    def testReplaceOrganizationJitEmailDomainsRequest(self):
        """Test ReplaceOrganizationJitEmailDomainsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
