# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.update_application_request import UpdateApplicationRequest

class TestUpdateApplicationRequest(unittest.TestCase):
    """UpdateApplicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateApplicationRequest:
        """Test UpdateApplicationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateApplicationRequest`
        """
        model = UpdateApplicationRequest()
        if include_optional:
            return UpdateApplicationRequest(
                name = '0',
                description = '',
                oidc_client_metadata = py_logto.models.update_application_request_oidc_client_metadata.UpdateApplication_request_oidcClientMetadata(
                    redirect_uris = [
                        null
                        ], 
                    post_logout_redirect_uris = [
                        ''
                        ], 
                    backchannel_logout_uri = '', 
                    backchannel_logout_session_required = True, 
                    logo_uri = '', ),
                custom_client_metadata = py_logto.models.list_applications_200_response_inner_custom_client_metadata.ListApplications_200_response_inner_customClientMetadata(
                    cors_allowed_origins = [
                        '0'
                        ], 
                    id_token_ttl = 1.337, 
                    refresh_token_ttl = 1.337, 
                    refresh_token_ttl_in_days = 1.337, 
                    tenant_id = '', 
                    always_issue_refresh_token = True, 
                    rotate_refresh_token = True, ),
                protected_app_metadata = py_logto.models.update_application_request_protected_app_metadata.UpdateApplication_request_protectedAppMetadata(
                    origin = '', 
                    session_duration = 1.337, 
                    page_rules = [
                        py_logto.models.list_applications_200_response_inner_protected_app_metadata_page_rules_inner.ListApplications_200_response_inner_protectedAppMetadata_pageRules_inner(
                            path = '', )
                        ], ),
                is_admin = True
            )
        else:
            return UpdateApplicationRequest(
        )
        """

    def testUpdateApplicationRequest(self):
        """Test UpdateApplicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
