# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.verify_verification_code_request import VerifyVerificationCodeRequest

class TestVerifyVerificationCodeRequest(unittest.TestCase):
    """VerifyVerificationCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyVerificationCodeRequest:
        """Test VerifyVerificationCodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyVerificationCodeRequest`
        """
        model = VerifyVerificationCodeRequest()
        if include_optional:
            return VerifyVerificationCodeRequest(
                email = 'k@?x!u'K}qz^sEC)lJ*=-jQ+'6`%cClu,k'!'su[..zF6V,V6rEtCO?&28nxs#k8z)\"\\6\\%TMxo:-sWVoim9gs',
                verification_code = '0',
                phone = '4'
            )
        else:
            return VerifyVerificationCodeRequest(
                email = 'k@?x!u'K}qz^sEC)lJ*=-jQ+'6`%cClu,k'!'su[..zF6V,V6rEtCO?&28nxs#k8z)\"\\6\\%TMxo:-sWVoim9gs',
                verification_code = '0',
                phone = '4',
        )
        """

    def testVerifyVerificationCodeRequest(self):
        """Test VerifyVerificationCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
