# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_connectors_get200_response_inner_form_items_inner_one_of_show_conditions_inner import ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner

class TestApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner(unittest.TestCase):
    """ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner:
        """Test ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner`
        """
        model = ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner()
        if include_optional:
            return ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner(
                target_key = '',
                expect_value = {}
            )
        else:
            return ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner(
                target_key = '',
        )
        """

    def testApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner(self):
        """Test ApiConnectorsGet200ResponseInnerFormItemsInnerOneOfShowConditionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
