# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_interaction_verification_webauthn_registration_post200_response import ApiInteractionVerificationWebauthnRegistrationPost200Response

class TestApiInteractionVerificationWebauthnRegistrationPost200Response(unittest.TestCase):
    """ApiInteractionVerificationWebauthnRegistrationPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiInteractionVerificationWebauthnRegistrationPost200Response:
        """Test ApiInteractionVerificationWebauthnRegistrationPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiInteractionVerificationWebauthnRegistrationPost200Response`
        """
        model = ApiInteractionVerificationWebauthnRegistrationPost200Response()
        if include_optional:
            return ApiInteractionVerificationWebauthnRegistrationPost200Response(
                rp = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_rp._api_interaction_verification_webauthn_registration_post_200_response_rp(
                    name = '', 
                    id = '', ),
                user = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_user._api_interaction_verification_webauthn_registration_post_200_response_user(
                    id = '', 
                    name = '', 
                    display_name = '', ),
                challenge = '',
                pub_key_cred_params = [
                    py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_pub_key_cred_params_inner._api_interaction_verification_webauthn_registration_post_200_response_pubKeyCredParams_inner(
                        type = '', 
                        alg = 1.337, )
                    ],
                timeout = 1.337,
                exclude_credentials = [
                    py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_exclude_credentials_inner._api_interaction_verification_webauthn_registration_post_200_response_excludeCredentials_inner(
                        type = '', 
                        id = '', 
                        transports = [
                            'usb'
                            ], )
                    ],
                authenticator_selection = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_authenticator_selection._api_interaction_verification_webauthn_registration_post_200_response_authenticatorSelection(
                    authenticator_attachment = 'platform', 
                    require_resident_key = True, 
                    resident_key = 'discouraged', 
                    user_verification = 'required', ),
                attestation = 'none',
                extensions = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_extensions._api_interaction_verification_webauthn_registration_post_200_response_extensions(
                    appid = '', 
                    cred_props = True, 
                    hmac_create_secret = True, )
            )
        else:
            return ApiInteractionVerificationWebauthnRegistrationPost200Response(
                rp = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_rp._api_interaction_verification_webauthn_registration_post_200_response_rp(
                    name = '', 
                    id = '', ),
                user = py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_user._api_interaction_verification_webauthn_registration_post_200_response_user(
                    id = '', 
                    name = '', 
                    display_name = '', ),
                challenge = '',
                pub_key_cred_params = [
                    py_logto.models._api_interaction_verification_webauthn_registration_post_200_response_pub_key_cred_params_inner._api_interaction_verification_webauthn_registration_post_200_response_pubKeyCredParams_inner(
                        type = '', 
                        alg = 1.337, )
                    ],
        )
        """

    def testApiInteractionVerificationWebauthnRegistrationPost200Response(self):
        """Test ApiInteractionVerificationWebauthnRegistrationPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
