# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.api_logs_get200_response_inner_payload_error import ApiLogsGet200ResponseInnerPayloadError

class TestApiLogsGet200ResponseInnerPayloadError(unittest.TestCase):
    """ApiLogsGet200ResponseInnerPayloadError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiLogsGet200ResponseInnerPayloadError:
        """Test ApiLogsGet200ResponseInnerPayloadError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiLogsGet200ResponseInnerPayloadError`
        """
        model = ApiLogsGet200ResponseInnerPayloadError()
        if include_optional:
            return ApiLogsGet200ResponseInnerPayloadError(
            )
        else:
            return ApiLogsGet200ResponseInnerPayloadError(
        )
        """

    def testApiLogsGet200ResponseInnerPayloadError(self):
        """Test ApiLogsGet200ResponseInnerPayloadError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
