# coding: utf-8

"""
    Logto API references

    API references for Logto services.

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.list_jwt_customizers200_response_inner_one_of1 import ListJwtCustomizers200ResponseInnerOneOf1

class TestListJwtCustomizers200ResponseInnerOneOf1(unittest.TestCase):
    """ListJwtCustomizers200ResponseInnerOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListJwtCustomizers200ResponseInnerOneOf1:
        """Test ListJwtCustomizers200ResponseInnerOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListJwtCustomizers200ResponseInnerOneOf1`
        """
        model = ListJwtCustomizers200ResponseInnerOneOf1()
        if include_optional:
            return ListJwtCustomizers200ResponseInnerOneOf1(
                key = '',
                value = py_logto.models.get_jwt_customizer_200_response_one_of_1.GetJwtCustomizer_200_response_oneOf_1(
                    script = '', 
                    environment_variables = {
                        'key' : ''
                        }, 
                    context_sample = py_logto.models.context_sample.contextSample(), 
                    token_sample = py_logto.models.get_jwt_customizer_200_response_one_of_1_token_sample.GetJwtCustomizer_200_response_oneOf_1_tokenSample(
                        jti = '', 
                        aud = null, 
                        scope = '', 
                        client_id = '', 
                        kind = '', ), )
            )
        else:
            return ListJwtCustomizers200ResponseInnerOneOf1(
                key = '',
                value = py_logto.models.get_jwt_customizer_200_response_one_of_1.GetJwtCustomizer_200_response_oneOf_1(
                    script = '', 
                    environment_variables = {
                        'key' : ''
                        }, 
                    context_sample = py_logto.models.context_sample.contextSample(), 
                    token_sample = py_logto.models.get_jwt_customizer_200_response_one_of_1_token_sample.GetJwtCustomizer_200_response_oneOf_1_tokenSample(
                        jti = '', 
                        aud = null, 
                        scope = '', 
                        client_id = '', 
                        kind = '', ), ),
        )
        """

    def testListJwtCustomizers200ResponseInnerOneOf1(self):
        """Test ListJwtCustomizers200ResponseInnerOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
