# coding: utf-8

"""
    Python SDK for Logto API

    Python SDK for Logto API.  Note: This SDK is for Logto Cloud and OSS. However, if you are using Logto OSS, some features available in the SDK may not work for you. Please refer to the response of `/api/swagger.json` endpoint on your Logto OSS instance for features available to you.

    The version of the OpenAPI document: 1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_logto.models.list_custom_phrases200_response_inner import ListCustomPhrases200ResponseInner

class TestListCustomPhrases200ResponseInner(unittest.TestCase):
    """ListCustomPhrases200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCustomPhrases200ResponseInner:
        """Test ListCustomPhrases200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCustomPhrases200ResponseInner`
        """
        model = ListCustomPhrases200ResponseInner()
        if include_optional:
            return ListCustomPhrases200ResponseInner(
                tenant_id = '',
                id = '0',
                language_tag = '0',
                translation = {"input":{"username":"Username","password":"Password"},"action":{"sign_in":"Sign In","continue":"Continue"}}
            )
        else:
            return ListCustomPhrases200ResponseInner(
                tenant_id = '',
                id = '0',
                language_tag = '0',
                translation = {"input":{"username":"Username","password":"Password"},"action":{"sign_in":"Sign In","continue":"Continue"}},
        )
        """

    def testListCustomPhrases200ResponseInner(self):
        """Test ListCustomPhrases200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
