# coding: utf-8

"""
    Logto API references

    API references for Logto services. To learn more about how to interact with Logto APIs, see [Interact with Management API](https://docs.logto.io/docs/recipes/interact-with-management-api/).

    The version of the OpenAPI document: Cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from py_logto.models.api_applications_get200_response_inner_oidc_client_metadata_redirect_uris_inner import ApiApplicationsGet200ResponseInnerOidcClientMetadataRedirectUrisInner
from typing import Optional, Set
from typing_extensions import Self

class ApiApplicationsGet200ResponseInnerOidcClientMetadata(BaseModel):
    """
    ApiApplicationsGet200ResponseInnerOidcClientMetadata
    """ # noqa: E501
    redirect_uris: List[ApiApplicationsGet200ResponseInnerOidcClientMetadataRedirectUrisInner] = Field(alias="redirectUris")
    post_logout_redirect_uris: List[StrictStr] = Field(alias="postLogoutRedirectUris")
    logo_uri: Optional[StrictStr] = Field(default=None, alias="logoUri")
    __properties: ClassVar[List[str]] = ["redirectUris", "postLogoutRedirectUris", "logoUri"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiApplicationsGet200ResponseInnerOidcClientMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in redirect_uris (list)
        _items = []
        if self.redirect_uris:
            for _item in self.redirect_uris:
                if _item:
                    _items.append(_item.to_dict())
            _dict['redirectUris'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiApplicationsGet200ResponseInnerOidcClientMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "redirectUris": [ApiApplicationsGet200ResponseInnerOidcClientMetadataRedirectUrisInner.from_dict(_item) for _item in obj["redirectUris"]] if obj.get("redirectUris") is not None else None,
            "postLogoutRedirectUris": obj.get("postLogoutRedirectUris"),
            "logoUri": obj.get("logoUri")
        })
        return _obj


